CUDA_VISIBLE_DEVICES=4 python test_specinfer.py --model  JackFram/llama-68m   --target meta-llama/Llama-2-13b-hf  --T 0.6 --P 1.0 --B 10  --DP 0.99 --W 32 --start 0 --end 200 --M 800 --growmap /home/zhuoming/Sequoia2/growmaps/16x1-tree.pt  --Mode greedy --dataset cnn >> results_abY.log
CUDA_VISIBLE_DEVICES=4 python test_specinfer.py --model  JackFram/llama-68m   --target meta-llama/Llama-2-13b-hf  --T 0.6 --P 1.0 --B 10  --DP 0.99 --W 32 --start 0 --end 200 --M 800 --growmap /home/zhuoming/Sequoia2/growmaps/16x2-tree.pt  --Mode greedy --dataset cnn >> results_abY.log
CUDA_VISIBLE_DEVICES=4 python test_specinfer.py --model  JackFram/llama-68m   --target meta-llama/Llama-2-13b-hf  --T 0.6 --P 1.0 --B 10  --DP 0.99 --W 32 --start 0 --end 200 --M 800 --growmap /home/zhuoming/Sequoia2/growmaps/16x4-tree.pt  --Mode greedy --dataset cnn >> results_abY.log
CUDA_VISIBLE_DEVICES=4 python test_specinfer.py --model  JackFram/llama-68m   --target meta-llama/Llama-2-13b-hf  --T 0.6 --P 1.0 --B 10  --DP 0.99 --W 32 --start 0 --end 200 --M 800 --growmap /home/zhuoming/Sequoia2/growmaps/16x8-tree.pt  --Mode greedy --dataset cnn >> results_abY.log
CUDA_VISIBLE_DEVICES=4 python test_specinfer.py --model  JackFram/llama-68m   --target meta-llama/Llama-2-13b-hf  --T 0.6 --P 1.0 --B 10  --DP 0.99 --W 32 --start 0 --end 200 --M 800 --growmap /home/zhuoming/Sequoia2/growmaps/16x16-tree.pt  --Mode greedy --dataset cnn >> results_abY.log
CUDA_VISIBLE_DEVICES=4 python test_specinfer.py --model  JackFram/llama-68m   --target meta-llama/Llama-2-13b-hf  --T 0.6 --P 1.0 --B 10  --DP 0.99 --W 32 --start 0 --end 200 --M 800 --growmap /home/zhuoming/Sequoia2/growmaps/16x32-tree.pt  --Mode greedy --dataset cnn >> results_abY.log

CUDA_VISIBLE_DEVICES=4 python test_specinfer.py --model  JackFram/llama-68m   --target meta-llama/Llama-2-13b-hf  --T 0.6 --P 1.0 --B 10  --DP 0.99 --W 32 --start 0 --end 200 --M 800 --growmap /home/zhuoming/Sequoia2/growmaps/32x1-tree.pt  --Mode greedy --dataset cnn >> results_abY.log
CUDA_VISIBLE_DEVICES=4 python test_specinfer.py --model  JackFram/llama-68m   --target meta-llama/Llama-2-13b-hf  --T 0.6 --P 1.0 --B 10  --DP 0.99 --W 32 --start 0 --end 200 --M 800 --growmap /home/zhuoming/Sequoia2/growmaps/32x2-tree.pt  --Mode greedy --dataset cnn >> results_abY.log
CUDA_VISIBLE_DEVICES=4 python test_specinfer.py --model  JackFram/llama-68m   --target meta-llama/Llama-2-13b-hf  --T 0.6 --P 1.0 --B 10  --DP 0.99 --W 32 --start 0 --end 200 --M 800 --growmap /home/zhuoming/Sequoia2/growmaps/32x4-tree.pt  --Mode greedy --dataset cnn >> results_abY.log
CUDA_VISIBLE_DEVICES=4 python test_specinfer.py --model  JackFram/llama-68m   --target meta-llama/Llama-2-13b-hf  --T 0.6 --P 1.0 --B 10  --DP 0.99 --W 32 --start 0 --end 200 --M 800 --growmap /home/zhuoming/Sequoia2/growmaps/32x8-tree.pt  --Mode greedy --dataset cnn >> results_abY.log
CUDA_VISIBLE_DEVICES=4 python test_specinfer.py --model  JackFram/llama-68m   --target meta-llama/Llama-2-13b-hf  --T 0.6 --P 1.0 --B 10  --DP 0.99 --W 32 --start 0 --end 200 --M 800 --growmap /home/zhuoming/Sequoia2/growmaps/32x16-tree.pt  --Mode greedy --dataset cnn >> results_abY.log

