CUDA_VISIBLE_DEVICES=3 python test_specinfer.py --model  JackFram/llama-68m   --target meta-llama/Llama-2-13b-hf  --T 0.6 --P 1.0 --B 10  --DP 0.99 --W 32 --start 0 --end 200 --M 800 --growmap /home/zhuoming/Sequoia2/growmaps/4x1-tree.pt  --Mode greedy --dataset cnn >> results_abX.log
CUDA_VISIBLE_DEVICES=3 python test_specinfer.py --model  JackFram/llama-68m   --target meta-llama/Llama-2-13b-hf  --T 0.6 --P 1.0 --B 10  --DP 0.99 --W 32 --start 0 --end 200 --M 800 --growmap /home/zhuoming/Sequoia2/growmaps/4x2-tree.pt  --Mode greedy --dataset cnn >> results_abX.log
CUDA_VISIBLE_DEVICES=3 python test_specinfer.py --model  JackFram/llama-68m   --target meta-llama/Llama-2-13b-hf  --T 0.6 --P 1.0 --B 10  --DP 0.99 --W 32 --start 0 --end 200 --M 800 --growmap /home/zhuoming/Sequoia2/growmaps/4x4-tree.pt  --Mode greedy --dataset cnn >> results_abX.log
CUDA_VISIBLE_DEVICES=3 python test_specinfer.py --model  JackFram/llama-68m   --target meta-llama/Llama-2-13b-hf  --T 0.6 --P 1.0 --B 10  --DP 0.99 --W 32 --start 0 --end 200 --M 800 --growmap /home/zhuoming/Sequoia2/growmaps/4x8-tree.pt  --Mode greedy --dataset cnn >> results_abX.log
CUDA_VISIBLE_DEVICES=3 python test_specinfer.py --model  JackFram/llama-68m   --target meta-llama/Llama-2-13b-hf  --T 0.6 --P 1.0 --B 10  --DP 0.99 --W 32 --start 0 --end 200 --M 800 --growmap /home/zhuoming/Sequoia2/growmaps/4x16-tree.pt  --Mode greedy --dataset cnn >> results_abX.log
CUDA_VISIBLE_DEVICES=3 python test_specinfer.py --model  JackFram/llama-68m   --target meta-llama/Llama-2-13b-hf  --T 0.6 --P 1.0 --B 10  --DP 0.99 --W 32 --start 0 --end 200 --M 800 --growmap /home/zhuoming/Sequoia2/growmaps/4x32-tree.pt  --Mode greedy --dataset cnn >> results_abX.log
CUDA_VISIBLE_DEVICES=3 python test_specinfer.py --model  JackFram/llama-68m   --target meta-llama/Llama-2-13b-hf  --T 0.6 --P 1.0 --B 10  --DP 0.99 --W 32 --start 0 --end 200 --M 800 --growmap /home/zhuoming/Sequoia2/growmaps/4x64-tree.pt  --Mode greedy --dataset cnn >> results_abX.log
CUDA_VISIBLE_DEVICES=3 python test_specinfer.py --model  JackFram/llama-68m   --target meta-llama/Llama-2-13b-hf  --T 0.6 --P 1.0 --B 10  --DP 0.99 --W 32 --start 0 --end 200 --M 800 --growmap /home/zhuoming/Sequoia2/growmaps/4x128-tree.pt  --Mode greedy --dataset cnn >> results_abX.log

CUDA_VISIBLE_DEVICES=3 python test_specinfer.py --model  JackFram/llama-68m   --target meta-llama/Llama-2-13b-hf  --T 0.6 --P 1.0 --B 10  --DP 0.99 --W 32 --start 0 --end 200 --M 800 --growmap /home/zhuoming/Sequoia2/growmaps/8x1-tree.pt  --Mode greedy --dataset cnn >> results_abX.log
CUDA_VISIBLE_DEVICES=3 python test_specinfer.py --model  JackFram/llama-68m   --target meta-llama/Llama-2-13b-hf  --T 0.6 --P 1.0 --B 10  --DP 0.99 --W 32 --start 0 --end 200 --M 800 --growmap /home/zhuoming/Sequoia2/growmaps/8x2-tree.pt  --Mode greedy --dataset cnn >> results_abX.log
CUDA_VISIBLE_DEVICES=3 python test_specinfer.py --model  JackFram/llama-68m   --target meta-llama/Llama-2-13b-hf  --T 0.6 --P 1.0 --B 10  --DP 0.99 --W 32 --start 0 --end 200 --M 800 --growmap /home/zhuoming/Sequoia2/growmaps/8x4-tree.pt  --Mode greedy --dataset cnn >> results_abX.log
CUDA_VISIBLE_DEVICES=3 python test_specinfer.py --model  JackFram/llama-68m   --target meta-llama/Llama-2-13b-hf  --T 0.6 --P 1.0 --B 10  --DP 0.99 --W 32 --start 0 --end 200 --M 800 --growmap /home/zhuoming/Sequoia2/growmaps/8x8-tree.pt  --Mode greedy --dataset cnn >> results_abX.log
CUDA_VISIBLE_DEVICES=3 python test_specinfer.py --model  JackFram/llama-68m   --target meta-llama/Llama-2-13b-hf  --T 0.6 --P 1.0 --B 10  --DP 0.99 --W 32 --start 0 --end 200 --M 800 --growmap /home/zhuoming/Sequoia2/growmaps/8x16-tree.pt  --Mode greedy --dataset cnn >> results_abX.log
CUDA_VISIBLE_DEVICES=3 python test_specinfer.py --model  JackFram/llama-68m   --target meta-llama/Llama-2-13b-hf  --T 0.6 --P 1.0 --B 10  --DP 0.99 --W 32 --start 0 --end 200 --M 800 --growmap /home/zhuoming/Sequoia2/growmaps/8x32-tree.pt  --Mode greedy --dataset cnn >> results_abX.log
CUDA_VISIBLE_DEVICES=3 python test_specinfer.py --model  JackFram/llama-68m   --target meta-llama/Llama-2-13b-hf  --T 0.6 --P 1.0 --B 10  --DP 0.99 --W 32 --start 0 --end 200 --M 800 --growmap /home/zhuoming/Sequoia2/growmaps/8x64-tree.pt  --Mode greedy --dataset cnn >> results_abX.log

# CUDA_VISIBLE_DEVICES=3 python test_specinfer.py --model  JackFram/llama-68m   --target meta-llama/Llama-2-13b-hf  --T 0.6 --P 1.0 --B 10  --DP 0.99 --W 32 --start 0 --end 200 --M 800 --growmap /home/zhuoming/Sequoia2/growmaps/16x1-tree.pt  --Mode greedy --dataset cnn >> results_abX.log
# CUDA_VISIBLE_DEVICES=3 python test_specinfer.py --model  JackFram/llama-68m   --target meta-llama/Llama-2-13b-hf  --T 0.6 --P 1.0 --B 10  --DP 0.99 --W 32 --start 0 --end 200 --M 800 --growmap /home/zhuoming/Sequoia2/growmaps/16x2-tree.pt  --Mode greedy --dataset cnn >> results_abX.log
# CUDA_VISIBLE_DEVICES=3 python test_specinfer.py --model  JackFram/llama-68m   --target meta-llama/Llama-2-13b-hf  --T 0.6 --P 1.0 --B 10  --DP 0.99 --W 32 --start 0 --end 200 --M 800 --growmap /home/zhuoming/Sequoia2/growmaps/16x4-tree.pt  --Mode greedy --dataset cnn >> results_abX.log
# CUDA_VISIBLE_DEVICES=3 python test_specinfer.py --model  JackFram/llama-68m   --target meta-llama/Llama-2-13b-hf  --T 0.6 --P 1.0 --B 10  --DP 0.99 --W 32 --start 0 --end 200 --M 800 --growmap /home/zhuoming/Sequoia2/growmaps/16x8-tree.pt  --Mode greedy --dataset cnn >> results_abX.log
# CUDA_VISIBLE_DEVICES=3 python test_specinfer.py --model  JackFram/llama-68m   --target meta-llama/Llama-2-13b-hf  --T 0.6 --P 1.0 --B 10  --DP 0.99 --W 32 --start 0 --end 200 --M 800 --growmap /home/zhuoming/Sequoia2/growmaps/16x16-tree.pt  --Mode greedy --dataset cnn >> results_abX.log
# CUDA_VISIBLE_DEVICES=3 python test_specinfer.py --model  JackFram/llama-68m   --target meta-llama/Llama-2-13b-hf  --T 0.6 --P 1.0 --B 10  --DP 0.99 --W 32 --start 0 --end 200 --M 800 --growmap /home/zhuoming/Sequoia2/growmaps/16x32-tree.pt  --Mode greedy --dataset cnn >> results_abX.log

# CUDA_VISIBLE_DEVICES=3 python test_specinfer.py --model  JackFram/llama-68m   --target meta-llama/Llama-2-13b-hf  --T 0.6 --P 1.0 --B 10  --DP 0.99 --W 32 --start 0 --end 200 --M 800 --growmap /home/zhuoming/Sequoia2/growmaps/32x1-tree.pt  --Mode greedy --dataset cnn >> results_abX.log
# CUDA_VISIBLE_DEVICES=3 python test_specinfer.py --model  JackFram/llama-68m   --target meta-llama/Llama-2-13b-hf  --T 0.6 --P 1.0 --B 10  --DP 0.99 --W 32 --start 0 --end 200 --M 800 --growmap /home/zhuoming/Sequoia2/growmaps/32x2-tree.pt  --Mode greedy --dataset cnn >> results_abX.log
# CUDA_VISIBLE_DEVICES=3 python test_specinfer.py --model  JackFram/llama-68m   --target meta-llama/Llama-2-13b-hf  --T 0.6 --P 1.0 --B 10  --DP 0.99 --W 32 --start 0 --end 200 --M 800 --growmap /home/zhuoming/Sequoia2/growmaps/32x4-tree.pt  --Mode greedy --dataset cnn >> results_abX.log
# CUDA_VISIBLE_DEVICES=3 python test_specinfer.py --model  JackFram/llama-68m   --target meta-llama/Llama-2-13b-hf  --T 0.6 --P 1.0 --B 10  --DP 0.99 --W 32 --start 0 --end 200 --M 800 --growmap /home/zhuoming/Sequoia2/growmaps/32x8-tree.pt  --Mode greedy --dataset cnn >> results_abX.log
# CUDA_VISIBLE_DEVICES=3 python test_specinfer.py --model  JackFram/llama-68m   --target meta-llama/Llama-2-13b-hf  --T 0.6 --P 1.0 --B 10  --DP 0.99 --W 32 --start 0 --end 200 --M 800 --growmap /home/zhuoming/Sequoia2/growmaps/32x16-tree.pt  --Mode greedy --dataset cnn >> results_abX.log

