#CUDA_VISIBLE_DEVICES=2 python testbed_greedy.py --model meta-llama/Llama-2-7b-hf   --target meta-llama/Llama-2-70b-hf  --T 0.6 --P 1.0 --B 10  --DP 0.99 --W 32 --start 0 --end 50 --Mode greedy  --M 1024 --growmap  /home/zhuominc/workspace/Sequoia/growmaps/L40-OpenWebText-7b-70b-greedy.pt  --offloading --dataset openwebtext >> results_greedy_openwebtext.log

CUDA_VISIBLE_DEVICES=0 python testbed.py --model meta-llama/Llama-2-7b-hf   --target meta-llama/Llama-2-70b-hf  --T 0.6 --P 1.0 --B 10  --DP 0.99 --W 32 --start 0 --end 100 --Mode greedy  --M 1024 --growmap  /home/zhuominc/workspace/Sequoia/growmaps/L40-CNN-7b-70b-stochastic-2.pt  --offloading --dataset cnn >> results_o4.log
CUDA_VISIBLE_DEVICES=0 python testbed.py --model meta-llama/Llama-2-7b-hf   --target meta-llama/Llama-2-70b-hf  --T 0.6 --P 1.0 --B 10  --DP 0.99 --W 32 --start 0 --end 100 --Mode greedy  --M 1024 --growmap  /home/zhuominc/workspace/Sequoia/growmaps/L40-C4-7b-70b-stochastic-2.pt  --offloading >> results_o4.log
CUDA_VISIBLE_DEVICES=0 python testbed.py --model meta-llama/Llama-2-7b-hf   --target meta-llama/Llama-2-70b-hf  --T 0.6 --P 1.0 --B 10  --DP 0.99 --W 32 --start 0 --end 100 --Mode greedy  --M 1024 --growmap  /home/zhuominc/workspace/Sequoia/growmaps/L40-OpenWebText-7b-70b-stochastic-2.pt  --offloading --dataset openwebtext >> results_o4.log

CUDA_VISIBLE_DEVICES=0 python testbed_greedy.py --model meta-llama/Llama-2-7b-hf   --target meta-llama/Llama-2-70b-hf  --T 0.6 --P 1.0 --B 10  --DP 0.99 --W 32 --start 0 --end 100 --Mode greedy  --M 1024 --growmap  /home/zhuominc/workspace/Sequoia/growmaps/L40-CNN-7b-70b-greedy-2.pt  --offloading --dataset cnn >> results_o4.log
CUDA_VISIBLE_DEVICES=0 python testbed_greedy.py --model meta-llama/Llama-2-7b-hf   --target meta-llama/Llama-2-70b-hf  --T 0.6 --P 1.0 --B 10  --DP 0.99 --W 32 --start 0 --end 100 --Mode greedy  --M 1024 --growmap  /home/zhuominc/workspace/Sequoia/growmaps/L40-C4-7b-70b-greedy-2.pt  --offloading >> results_o4.log
CUDA_VISIBLE_DEVICES=0 python testbed_greedy.py --model meta-llama/Llama-2-7b-hf   --target meta-llama/Llama-2-70b-hf  --T 0.6 --P 1.0 --B 10  --DP 0.99 --W 32 --start 0 --end 100 --Mode greedy  --M 1024 --growmap  /home/zhuominc/workspace/Sequoia/growmaps/L40-OpenWebText-7b-70b-greedy-2.pt  --offloading --dataset openwebtext >> results_o4.log
#CUDA_VISIBLE_DEVICES=2 python test_specinfer.py --model meta-llama/Llama-2-7b-hf   --target meta-llama/Llama-2-70b-hf  --T 0.6 --P 1.0 --B 10  --DP 0.99 --W 32 --start 0 --end 50 --Mode greedy  --M 1024 --growmap /home/zhuominc/workspace/Sequoia/growmaps/16x48-tree.pt  --offloading --dataset openwebtext >> results_stochastic_openwebtext.log
#CUDA_VISIBLE_DEVICES=2 python test_specinfer.py --model meta-llama/Llama-2-7b-hf   --target meta-llama/Llama-2-70b-hf  --T 0.6 --P 1.0 --B 10  --DP 0.99 --W 32 --start 0 --end 50 --Mode greedy  --M 1024 --growmap /home/zhuominc/workspace/Sequoia/growmaps/16x48-tree.pt  --offloading --dataset cnn >> results_stochastic_cnn.log

# CUDA_VISIBLE_DEVICES=2 python testbed_greedy.py --model meta-llama/Llama-2-7b-hf   --target meta-llama/Llama-2-70b-hf  --T 0.6 --P 1.0 --B 10  --DP 0.99 --W 32 --start 0 --end 50 --Mode greedy  --M 1024 --growmap /home/zhuominc/workspace/Sequoia/growmaps/16x48-tree.pt  --offloading >> results_greedy_c4.log
# CUDA_VISIBLE_DEVICES=2 python test_specinfer.py --model meta-llama/Llama-2-7b-hf   --target meta-llama/Llama-2-70b-hf  --T 0.6 --P 1.0 --B 10  --DP 0.99 --W 32 --start 0 --end 50 --Mode greedy  --M 1024 --growmap /home/zhuominc/workspace/Sequoia/growmaps/16x48-tree.pt  --offloading  >> results_stochastic_c4.log